// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_ROGDF_RCPPEXPORTS_H
#define RCPP_ROGDF_RCPPEXPORTS_H

#include <Rcpp.h>

RcppExport SEXP OGDF_rogdf_version();
RcppExport SEXP OGDF_rogdf_circular_layout(SEXP graphSEXP, SEXP minDistCircleSEXP, SEXP minDistLevelSEXP, SEXP minDistSiblingSEXP, SEXP minDistCCSEXP, SEXP pageRatioSEXP);
RcppExport SEXP OGDF_rogdf_tree_layout(SEXP graphSEXP, SEXP siblingDistanceSEXP, SEXP subtreeDistanceSEXP, SEXP levelDistanceSEXP, SEXP treeDistanceSEXP, SEXP orthogonalLayoutSEXP, SEXP orientationSEXP, SEXP selectRootSEXP);
RcppExport SEXP OGDF_rogdf_fmmm_layout(SEXP graphSEXP, SEXP optionsSEXP);

#endif
